M48
; DRILL file {KiCad 7.0.8} date Wed Feb 21 14:18:43 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-21T14:18:43-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X129.063Y-82.507
X129.063Y-111.507
X166.063Y-82.507
X166.063Y-111.507
T0
M30
